### ISSUE TITLE
SkyUX 3 applications (thanks to Angular 5+) no longer contain proper locale data

### ISSUE THREAD

**Issue by Blackbaud-ScottFreeman** [blackbaud/skyux-i18n#30]
### Expected behavior
Using the SkyUX framework should remove many mundane tasks from the user such has registering necessary locale data in order for i18n pipes to function correctly.  Ideally, there would be a way for SkyUX to dynamically register the appropriate locale during initialization.

### Actual behavior
Only locale data for `en-US` is registered by default.  Any other non-English locales need to be registered manually.  There are easily over 100 locales and teams aren't going to want to do this manually for each SPA.  Errors will being thrown when using an i18n pipe if a user's browser is set up to use a locale that has not be manually registered.

### Steps to reproduce

- Create a new SkyUX SPA and migrate to SkyUX3
- In the home component, add public property containing a Date
- In the home component template, add markup to display the date using the new SkyDatePipe `<div>{{myDate | skyDate:'short'}}</div>`
- Update your browser to use a non-English locale such as fr-CA
- Serve the SPA and notice that the pipe throws an error that can be seen in the console.
- Note `skyDate` uses the locale from `SKYUX_HOST` which angular pipes wouldn't do.  If using angular pipes, you must update app-extras.module.ts to provide the LOCALE_ID.

### Severity
Medium

When using something like `skyDate`, the best you can do is to provide all of the locales you think you will need, which isn't a perfect solution because we've already had bugs come in from users using Swedish locales.

If using a custom locale provider for angular pipes, you can flag all of the locales that you have registered and then fall back on `en-US` if the user's locale or parent locale hasn't been registered.

### Impact
High (if devs don't provide the necessary workarounds or if using skyDate)
Low (otherwise because it's more of an annoyances to fall back on en-US locale)

**Comment by Blackbaud-PaulCrowder** [comment]
Some initial research:

- The change from Angular 4 to Angular 5 was to no longer use the browser's `Intl` API to format dates and numbers in order to address browser compatibility concerns.  Instead, any supported locales must be imported manually. https://github.com/angular/angular/blob/master/CHANGELOG.md#features-28

- Simply including all the locale data files supplied by Angular causes the size of the app bundles to increase by 2.6 MB.

- There are articles about how to lazy-load locale data in an Angular application, but it's impractical for SKY UX to implement because it's highly dependent on the abilities of SKY UX builder/host and further couples the use of SKY UX to those parts of our tech stack.

- Our best option may be to include a subset of locales by default, and let SPAs register additional ones as they see fit.

**Comment by Blackbaud-ScottFreeman** [comment]
Something else that would be useful here is if skyux had a default locale to fallback on if a particular locale isn't registered.  If you currently set up Angular's LOCALE_ID to be a locale that wasn't registered, then the i18n pipes result in errors instead of using a default locale.  It's unlikely that the combination of a subset of locales provided by skyux along with extra locales provided by a team would cover enough locales that exist in the wild.  The Swedish locale that we already ran into was very surprising to me.

**Comment by Blackbaud-PaulCrowder** [comment]
If we went with a subset of locales, we would definitely implement fallback logic.

**Comment by Blackbaud-ScottFreeman** [comment]
I imagine that similar work would need to be done for SkyNumericPipe as well since it uses CurrencyPipe and DecimalPipe under the hood.  I believe that there are still scenarios where team can't use SkyNumericPipe for showing something like percentages where the PercentPipe is useful.  We would also need to communicate to developers to use the these SKYUX pipes since I believe that most teams are using the Angular DatePipe.
